//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Chess
//  @ File Name : GobangOperation.h
//  @ Date : 2017/1/9
//  @ Author : limuzi
//
//


#if !defined(_GOBANGOPERATION_H)
#define _GOBANGOPERATION_H

#include "ChessInterface/PieceOperation.h"

class GobangOperation : public PieceOperation {
public:
	bool canMove(const Board* board, const Step* step);

};

#endif  //_GOBANGOPERATION_H
