//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Chess
//  @ File Name : GobangPiece.cpp
//  @ Date : 2017/1/9
//  @ Author : limuzi
//
//


#include "GobangPiece.h"



GobangPiece::GobangPiece(short id, short r, short c, PieceOperation *operation, int value, bool side)
    :Piece(id,r,c,operation,value,side)
{

}

GobangPiece::~GobangPiece()
{

}



