//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Chess
//  @ File Name : GobangOperation.cpp
//  @ Date : 2017/1/9
//  @ Author : limuzi
//
//


#include "GobangOperation.h"

bool GobangOperation::canMove(const Board* board, const Step* step)
{
    bool flag = false ;

    return flag ;
}

