//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Chess
//  @ File Name : GobangPiece.h
//  @ Date : 2017/1/9
//  @ Author : limuzi
//
//


#if !defined(_GOBANGPIECE_H)
#define _GOBANGPIECE_H

#include "ChessInterface/Piece.h"

class GobangPiece : public Piece {

public:
    GobangPiece(short id, short r,short c ,PieceOperation *operation=NULL, int value=0, bool side=true) ;

    ~GobangPiece() ;

};

#endif  //_GOBANGPIECE_H
